DOCS-2369: Combine TrueCommand VM deploy instructions into main Insta…
truenas/documentation pull request #1001
Opened 2021-08-04 14:33 UTC by jervin777

…ll article

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2021-08-05 12:44 UTC, Mrt134 commented
Looks good, pinging @beanpole135 for a quick review

2021-08-05 14:02 UTC, beanpole135 commented
Looks like the HTML within the boxes is not rendering on the preview site:
![image](https://user-images.githubusercontent.com/4172864/128363180-6f87d20b-5718-40f2-ae97-8bf511a7494b.png)

2021-08-05 14:04 UTC, beanpole135 commented
Looking at the code more closely, that `</div>` in the second box should be at the end of the first box instead.

2021-08-05 15:58 UTC, Mrt134 requested changes
Added a few suggestions to clean up the div errors @beanpole135 mentioned.

2021-08-05 15:58 UTC, Mrt134 commented on content/TrueCommand/TCGettingStarted/Install/_index.md
> +{{< toc >}}
```suggestion

```

2021-08-05 15:58 UTC, Mrt134 commented on content/TrueCommand/TCGettingStarted/Install/_index.md
> +{{< tab "Debian" >}}
```suggestion
### Debian
```

2021-08-05 15:58 UTC, Mrt134 commented on content/TrueCommand/TCGettingStarted/Install/_index.md
> +{{< tab "Alpine" >}}
```suggestion

### Alpine
```

2021-08-05 15:58 UTC, Mrt134 commented on content/TrueCommand/TCGettingStarted/Install/_index.md
> +{{< tab "Void" >}}
```suggestion

### Void
```

2021-08-05 15:58 UTC, Mrt134 commented on content/TrueCommand/TCGettingStarted/Install/_index.md
> +{{< /tabs >}}
```suggestion

```

2021-08-06 17:52 UTC, Mrt134 approved these changes
Changes are addressed and this is ready for merge. I'm checking with Web team about setting up redirects or aliases for the vmdeploy URL that will be going offline before merging this one.

2021-08-09 13:59 UTC, Mrt134 commented
Opened https://jira.ixsystems.com/browse/DM-304 to notify the web team about the URL change and have approval to merge.

2021-08-09 15:07 UTC, Mrt134 commented
Link checker hit a temporary FreeBSD site outage - approved for merge.

2021-08-09 15:07 UTC, merged