DOCS-2398 SCALE: Interfaces article
truenas/documentation pull request #1011
Opened 2021-08-06 17:58 UTC by tonyriv3

2021-08-09 18:01 UTC, Mrt134 approved these changes

2021-08-09 18:02 UTC, Mrt134 requested changes

2021-08-09 18:02 UTC, Mrt134 commented on content/SCALE/Network/InterfacesSCALE.md
> +title: "Active Directory"
```suggestion
title: "Active Directory"
```
Needs a different title?

2021-08-09 18:14 UTC, tonyriv3 commented on content/SCALE/Network/InterfacesSCALE.md
> +title: "Active Directory"
Whoops! I'll fix it.

2021-08-10 14:14 UTC, Mrt134 commented
Combining this change into a single PR: https://github.com/truenas/documentation/pull/1016

2021-08-10 14:14 UTC, closed without merging