Docs 2641 publish scale network page video
truenas/documentation pull request #1187
Opened 2021-12-08 21:09 UTC by micjohnson777

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2021-12-09 13:50 UTC, Mrt134 reviewed
Found a couple typos.

2021-12-09 13:50 UTC, Mrt134 commented on content/SCALE/Network/_index.md
> +When users enable **TLS Crypt Auth Enabled**, TrueNAS generates a static key for the **TLS Crypt Aut*h* field after saving the options.
Typo fix
```suggestion
When users enable **TLS Crypt Auth Enabled**, TrueNAS generates a static key for the **TLS Crypt Auth** field after saving the options.
```

2021-12-09 13:50 UTC, Mrt134 commented on content/SCALE/Network/_index.md
> +Setting *S*tart Automatically** starts the service when TrueNAS completes booting and runs the network and data pools.
```suggestion
Setting **Start Automatically** starts the service when TrueNAS completes booting and runs the network and data pools.
```

2021-12-15 21:47 UTC, BonnieF requested changes
The video for /scale/Network/ "Networking Tour Video" expand area and the one under the Global configuration are playing the same video - even though they are named differently. Can you add the correct video to whichever one is wrong?

2021-12-15 22:09 UTC, tonyriv3 commented
@micjohnson777 
The two videos are identical. The `scaleangelfishnetworking` is the most up-to-date version, so you should only use that one.

2021-12-17 12:54 UTC, Mrt134 approved these changes

2021-12-17 13:02 UTC, Mrt134 commented
Link check hit one timeout issue with MIT PGP public key server. Did more digging and the key lookup function on the site is slow enough that the checker isn't likely to pass it. We'll either need to replace this URL with a link to a site that is more performant, or add an exception to the checker and run the risk of missing early warnings if something permanently changes about the link location.

2021-12-17 13:03 UTC, merged