DOCS-2999 Create parallel persistent L2ARC article for SCALE
truenas/documentation pull request #1217
Opened 2021-12-27 21:50 UTC by tonyriv3

Take the https://www.truenas.com/docs/core/notices/persistentl2arcin12.0/ article and create a parallel version for SCALE. See if there is common text that can be single-sourced, but ensure the SCALE article follows the SCALE UI / process for the procedure.

2021-12-28 13:31 UTC, Mrt134 requested changes
Good start! There are some adjustments needed for the content to use the SCALE image and reflect the SCALE UI a little closer.

2021-12-28 13:31 UTC, Mrt134 commented on content/SCALE/Notices/PersistentL2ARCinSCALE.md
> +title: "Persistent L2ARC in TrueNAS 12.0"
Rename for SCALE (12.0 doesn't apply)
```suggestion
title: "Persistent L2ARC in TrueNAS SCALE"
```

2021-12-28 13:31 UTC, Mrt134 commented on content/SCALE/Notices/PersistentL2ARCinSCALE.md
> +Persistent L2ARC, or L2ARC rebuild, is a ZFS feature that was added to TrueNAS 12.0.
```suggestion
Persistent L2ARC, or L2ARC rebuild, is a ZFS feature that was added to TrueNAS 12.0 and is also present in TrueNAS SCALE.
```

2021-12-28 13:31 UTC, Mrt134 commented on content/SCALE/Notices/PersistentL2ARCinSCALE.md
> +Because of this, persistent L2ARC is disabled by default in TrueNAS 12.0 and must be manually activated.
```suggestion
Because of this, persistent L2ARC is disabled by default in TrueNAS SCALE and must be manually activated.
```

2021-12-28 13:31 UTC, Mrt134 commented on content/SCALE/Notices/PersistentL2ARCinSCALE.md
> +Go to **System > Tunables > ADD**.
Adjusting for SCALE UI placement (reviewed SCALE 22.02-RC.2 system)
```suggestion
Go to **System Settings > Advanced**, find the **Sysctl** card and click **Add**.
```

2021-12-28 13:31 UTC, Mrt134 commented on content/SCALE/Notices/PersistentL2ARCinSCALE.md
> +For the *Variable*, enter `vfs.zfs.l2arc.rebuild_enabled`. Set the *Value* to *1* and the *Type* to *sysctl*.
Type field is not present in SCALE.
```suggestion
For the *Variable*, enter `vfs.zfs.l2arc.rebuild_enabled`. Set the *Value* to *1*.
```

2021-12-28 13:31 UTC, Mrt134 commented on content/SCALE/Notices/PersistentL2ARCinSCALE.md
> +Make sure *Enabled* is set and click *SUBMIT*.
```suggestion
Make sure *Enabled* is set and click *Save*.
```

2021-12-28 13:31 UTC, Mrt134 commented on content/SCALE/Notices/PersistentL2ARCinSCALE.md
> +![PersistentL2ARCTunable](/images/CORE/12.0/SystemTunablesL2ARCRebuild.png "Persistent L2ARC Activation")
Rewrite for SCALE image use.
```suggestion
![PersistentL2ARCSCALE](/images/SCALE/PersistentL2ARCSCALE.png "Persistent L2ARC Activation")
```

2021-12-29 14:27 UTC, tonyriv3 commented
@Mrt134 
Since we've switched this from a parallel SCALE article to updating the L2ARC reference article, should I switch from `master` to `13.0-Documentation`?

2021-12-29 14:46 UTC, Mrt134 commented
Agreed, I'll adjust the Jira ticket too.

2022-01-07 13:53 UTC, Mrt134 approved these changes

2022-01-07 13:53 UTC, merged