Docs-3451 SCALE 22.02 Reorg Permissions Article Content
truenas/documentation pull request #1455
Opened 2022-08-05 19:39 UTC by micjohnson777

This PR creates a new UI reference article for ACL editor screens, reorganizes the content in the how-to article, and updates screenshots.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2022-08-10 14:08 UTC, tonyriv3 requested changes

2022-08-10 14:08 UTC, tonyriv3 commented on content/SCALE/SCALEUIReference/Storage/Pools/EditACLScreens.md
> +Removing this permission results lost access to the path.
```suggestion
Removing this permission results in lost access to the path.
```

2022-08-10 14:08 UTC, tonyriv3 commented on content/SCALE/SCALEUIReference/Storage/Pools/EditACLScreens.md
> +The section below describe the differences between screens for each ACL type.
```suggestion
The section below describes the differences between screens for each ACL type.
```

2022-08-10 14:08 UTC, tonyriv3 commented on content/SCALE/SCALEUIReference/Storage/Pools/EditACLScreens.md
> +The **Access Control List** section displays the items and a permissions summary for the **owner@**, **group@** and **everyone@** for both POSIX and NSFv4 ACL types. The list of items changes based o
```suggestion
The **Access Control List** section displays the items and a permissions summary for the **owner@**, **group@**, and **everyone@** for both POSIX and NSFv4 ACL types. The list of items changes based on a selected pre-configured set of permissions.
```

2022-08-10 14:08 UTC, tonyriv3 commented on content/SCALE/SCALEUIReference/Storage/Pools/EditACLScreens.md
> +These functions display on the **Edit ACL** screen for both POSIX and NSFv4 ACL types except for **Strip ACL**, it only displays for NSFv4 types.
```suggestion
These functions display on the **Edit ACL** screen for both POSIX and NSFv4 ACL types except for **Strip ACL**, which only displays for NSFv4 types.
```

2022-08-10 15:16 UTC, micjohnson777 commented on content/SCALE/SCALEUIReference/Storage/Pools/EditACLScreens.md
> +TrueNAS SCALE offers two ACL types, POSIX which is the SCALE default, and NFSv4.
It is not allowing me to commit your suggestion for some reason. After Tim reviews, I'll make this change if it is not already in the article now.

2022-08-11 13:58 UTC, Mrt134 commented on content/SCALE/SCALEUIReference/Storage/Pools/EditACLScreens.md
> +TrueNAS SCALE offers two ACL types, POSIX which is the SCALE default, and NFSv4.
This change has already been made and is good to go

2022-08-11 15:15 UTC, tonyriv3 approved these changes

2022-08-11 15:17 UTC, merged