Docs-4188 SCALE 22.02 Updated Periodic Snapshot Task Articles
truenas/documentation pull request #1536
Opened 2022-09-24 18:50 UTC by micjohnson777

This commit updates the PeriodicSnapshotTaskScreenSCALE.md article to the UI ref format with new screenshots. It updates the PeriodicSnapshotTaskSCALE.md article tutorial content to a procedure flow with new section headers and internal references.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2022-09-28 21:04 UTC, tonyriv3 requested changes

2022-09-28 21:04 UTC, tonyriv3 commented on content/SCALE/SCALEUIReference/DataProtection/PeriodicSnapshotTasksScreensSCALE.md
> +The **State** on the list view does not link to the log file or anything else, it just displays the current state of the task.
```suggestion
The **State** on the list view does not link to the log file or anything else. It only displays the current state of the task.
```

2022-09-28 21:04 UTC, tonyriv3 commented on content/SCALE/SCALEUIReference/DataProtection/PeriodicSnapshotTasksScreensSCALE.md
> +Click the <span class="material-icons">expand_more</span> expand icon at the right of the task opens the details for the selected task.
```suggestion
Click the <span class="material-icons">expand_more</span> expand icon at the right of the task to open the details for the selected task.
```

2022-09-28 21:04 UTC, tonyriv3 commented on content/SCALE/SCALEUIReference/DataProtection/PeriodicSnapshotTasksScreensSCALE.md
> +The **Add Periodic Snapshot Task** and **Edit Periodic Snapshot Task** display the some of the same settings.
```suggestion
The **Add Periodic Snapshot Task** and **Edit Periodic Snapshot Task** screens display some of the same settings.
```

2022-09-29 15:41 UTC, micjohnson777 commented on content/SCALE/SCALEUIReference/DataProtection/PeriodicSnapshotTasksScreensSCALE.md
> +Each task listed is a link that opens the **[Edit Periodic Snapshot Task]()** screen populated with with the settings for that task. Click on the **Description**, **Frequency** or **Next Run** column
I need to fix that relref that is missing

2022-09-29 15:49 UTC, micjohnson777 commented
Pulled the branch up to fix issues with missing internal links and the the feedback marked Resolved

2022-09-29 15:53 UTC, tonyriv3 approved these changes

2022-09-29 15:53 UTC, merged