Update UsingApps.md
truenas/documentation pull request #1630
Opened 2022-12-07 15:08 UTC by tonyriv3

2022-12-13 14:01 UTC, Ornias1993 requested changes

2022-12-13 14:01 UTC, Ornias1993 commented on content/SCALE/SCALETutorials/Apps/UsingApps.md
>  ## Official Applications
```suggestion
### Official Applications
```

2022-12-13 14:01 UTC, Ornias1993 commented on content/SCALE/SCALETutorials/Apps/UsingApps.md
>  ## Official Applications
And the same on line49

2022-12-13 14:02 UTC, Ornias1993 commented on content/SCALE/SCALETutorials/Apps/UsingApps.md
>  Official containers are pre-configured to only require a name during deployment.
```suggestion
Official Apps are pre-configured to only require a name during deployment.
```

Apps =/= containers...

2022-12-14 18:21 UTC, micjohnson777 approved these changes

2022-12-14 18:25 UTC, merged