incidental typo fix
truenas/documentation pull request #1684
Opened 2023-01-04 18:25 UTC by Mrt134

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2023-01-04 21:54 UTC, clairewrtr commented on content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
> +{{< taglist tag="scaleafp" limit="10" title="Releated AFP Articles" >}}
```suggestion
{{< taglist tag="scaleafp" limit="10" title="Related AFP Articles" >}}
```

2023-01-04 21:55 UTC, clairewrtr commented on content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
>  #### Approving Apple Software Compatibility
```suggestion
#### Improving Apple Software Compatibility
```

2023-01-04 21:56 UTC, clairewrtr requested changes
Just a few questions...

2023-01-05 13:16 UTC, Mrt134 commented
Updated, thanks!

2023-01-05 13:22 UTC, clairewrtr approved these changes
Looks good.

2023-01-05 13:22 UTC, merged