PD-177 TC 2.3.1 Release Notes
truenas/documentation pull request #1725
Opened 2023-02-03 16:28 UTC by micjohnson777

This commit is the initial commit of the 2.3.1 hot patch/critical bug fix release.

The release schedule still needs to be updated.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2023-02-06 18:55 UTC, tonyriv3 requested changes

2023-02-06 18:55 UTC, tonyriv3 commented on content/TrueCommand/TCReleaseNotes.md
> +iXsystems is please to release TrueCommand 2.3.1!
```suggestion
iXsystems is pleased to release TrueCommand 2.3.1!
```

2023-02-08 16:15 UTC, tonyriv3 submitted a review, later dismissed

2023-02-16 13:48 UTC, Mrt134 approved these changes
Looks great!

2023-02-16 14:11 UTC, merged