PD-182 Add Restoring a Hot Spare to Replacing Disk Articles
truenas/documentation pull request #1863
Opened 2023-04-12 14:35 UTC by micjohnson777

This commit creates a snippet to use in both CORE and SCALE Replacing a Disk articles that covers restoring a hot spare to operation.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2023-04-12 20:04 UTC, tonyriv3 requested changes

2023-04-12 20:04 UTC, tonyriv3 commented on content/_includes/RestoreHotSpare.md
> +After a disk fails and the hot spare takes over, to restore the hot spare to a waiting status after you replace the failed drive, first remove the current hot spare from the pool, then add the spare
```suggestion
After a disk fails, the hot spare takes over. To restore the hot spare to waiting status after replacing the failed drive, remove the hot spare from the pool, then re-add it to the pool as a new hot spare.
```

2023-04-12 20:31 UTC, micjohnson777 commented
Ready to approve and merge! Thank you!!

2023-04-13 18:39 UTC, tonyriv3 approved these changes

2023-04-13 22:48 UTC, merged