Pd 324 add enterprise info to min io app articles
truenas/documentation pull request #1872
Opened 2023-04-18 18:29 UTC by micjohnson777

This PR makes changes to the SCALE Tutorial Applications articles navigation. It adds a new expand section for Enterprise Applications, and changes the weights of the other tutorial articles to have them display below the new section. The new _index.md article still needs a nuanced statement about Enterprise Apps verses Official Chart Apps.

It moves the existing EnterpriseApplicationsSCALE.md article to the new section, and adds a new article for configuring MinIO Official Enterprise using the minio wizard.

It updates content in the MinIO Official Charts tutorials. Adds a procedure overview to the MinioManualUpdate.md article, and updates content in MinIOClusterin.md article and replaces or removes out of date docker image screenshots.

It makes minor corrections in the Ui Ref article AppsScreensSCALE.md.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2023-04-18 18:58 UTC, Mrt134 requested changes
Looking good! I've got a few polish comments/suggestions.

2023-04-18 18:58 UTC, Mrt134 commented on content/SCALE/SCALETutorials/Apps/EnterpriseApps/ConfigMinioEnterprise.md
> +If your system includes shares (SMB, NFS, iSCSI), disable the share service before adding and configuring a the MinIO application.
```suggestion
If your system has active sharing configurations (SMB, NFS, iSCSI), disable these sharing services in **System Settings > Services** before adding and configuring the MinIO application.
```

2023-04-18 18:58 UTC, Mrt134 commented on content/SCALE/SCALETutorials/Apps/EnterpriseApps/ConfigMinioEnterprise.md
> +To use host path validation create a dataset for the application with a unique path. For example, */pool/shares/minio* for the share and */pool/apps/minio* for the application.
```suggestion
To use host path validation, create a dataset for the application with a unique path. For example, */pool/shares/minio* for the share and */pool/apps/minio* for the application.
```

2023-04-18 18:58 UTC, Mrt134 commented on content/SCALE/SCALETutorials/Apps/EnterpriseApps/ConfigMinioEnterprise.md
> +This basic procedure covers the required MinIO Enterprise settings.
```suggestion
This basic procedure covers the required Enterprise MinIO App settings.
```

2023-04-18 18:58 UTC, Mrt134 commented on content/SCALE/SCALETutorials/Apps/EnterpriseApps/ConfigMinioEnterprise.md
> +SCALE Enterprise single controller systems with the applications and virtual machines license have access to the **MinIO Official Enterprise** widget. Go to **Apps**, select the pool to use for appli
```suggestion
SCALE Enterprise single controller systems with the applications and virtual machines license feature have access to the **MinIO Official Enterprise** widget. Go to **Apps**, select the pool to use for applications, if not already selected, then click on the **Available Applications** screen.
```

2023-04-18 18:58 UTC, Mrt134 commented on content/SCALE/SCALETutorials/Apps/EnterpriseApps/ConfigMinioEnterprise.md
> +Enter a name for your MinIO application deployment if not using the default value. **Version** populates with the current MinIO version.
```suggestion
Enter a name for your MinIO application deployment. A default value is provided but can be overriden. **Version** populates with the current MinIO version.
```

2023-04-18 18:58 UTC, Mrt134 commented on content/SCALE/SCALETutorials/Apps/MinIOClustersSCALE/MinIOClustering.md
> +If your system has sharing (SMB, NFS, iSCSI) configured, disable the share service before adding and configuring a new MinIO deployment.
update according to the comment/suggestion above
```suggestion
If your system has sharing (SMB, NFS, iSCSI) configured, disable the share service before adding and configuring a new MinIO deployment. 
```

2023-04-18 18:58 UTC, Mrt134 commented on content/SCALE/SCALETutorials/Apps/MinIOClustersSCALE/MinIOClustering.md
> +To use host path validation set up a new dataset for the application with a completely different path. For example, for the share */pool/shares/minio* and for the application */pool/apps/minio*.
```suggestion
To use host path validation, set up a new dataset for the application with a completely different path. For example, for the share */pool/shares/minio* and for the application */pool/apps/minio*.
```

2023-04-18 18:58 UTC, Mrt134 commented on content/SCALE/SCALETutorials/Apps/MinIOClustersSCALE/MinIOClustering.md
> +Select **Enable Distributed Mode** if setting up a cluster of SCALE systems in a distributed cluster.
```suggestion
Select **Enable Distributed Mode** when setting up a cluster of SCALE systems in a distributed cluster. 
```

2023-04-18 19:08 UTC, micjohnson777 commented
Thank you for the polish points! I did have to fix some stray ``` in the first article but other than that, all comments committed!

2023-04-19 11:59 UTC, Mrt134 approved these changes

2023-04-19 11:59 UTC, merged