PD-356   CORE 13 U5 Improve View Enclosure Article Content
truenas/documentation pull request #1910
Opened 2023-05-18 21:28 UTC by tonyriv3

2023-05-19 11:44 UTC, micjohnson777 requested changes
Looks great, but in the SCALE article, please change the image shortcodes to the new version if you have the time.

2023-05-22 17:09 UTC, DjP-iX requested changes

2023-05-22 17:09 UTC, DjP-iX commented on content/SCALE/SCALEUIReference/SystemSettings/EnclosureScreensSCALE.md
> +TrueNAS Mini and R30 systems does not include the **IDENTIFY DRIVE** function.
```suggestion
TrueNAS Mini and R30 systems do not include the **IDENTIFY DRIVE** function. 
```

2023-05-25 15:32 UTC, Mrt134 approved these changes

2023-05-25 15:32 UTC, merged