PD-366   TrueNAS Hardware/Software Compatibility Matrix
truenas/documentation pull request #1943
Opened 2023-05-31 18:40 UTC by tonyriv3

2023-06-01 18:24 UTC, micjohnson777 commented on content/Hardware/_index.md
>  The TrueNAS R-Series is a family of single controller systems that leverage ZFS and TrueNAS to provide the industry's best storage value.
possessive case, suggest this as an alternative
```suggestion
The TrueNAS R-Series is a family of single controller systems that leverage ZFS and TrueNAS to provide the best storage value in the industry.
```

2023-06-01 18:30 UTC, micjohnson777 submitted a review, later dismissed
Looks great, only one thing found with a possessive case. Excellent work!

2023-06-02 18:02 UTC, Mrt134 commented on content/Hardware/_index.md
> +| F1 | <span class="iconify" data-icon="oi:x"></span> No | <span class="iconify" data-icon="oi:check"></span> Yes |
```suggestion
```

2023-06-02 18:03 UTC, Mrt134 requested changes
I want to hold back on this for one final sanity check upstream.

2023-06-29 12:30 UTC, closed without merging