PD-487: Update TrueNAS Security Best Practices
truenas/documentation pull request #1947
Opened 2023-06-01 14:52 UTC by Mrt134

This adds a general best practices section in front of the specific service hardening content and reweights headers for better navigation.
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2023-06-01 17:50 UTC, kmoore134 requested changes

2023-06-01 17:50 UTC, kmoore134 commented on content/Solutions/Optimizations/Security.md
> +description: "Best practices to minimize security vulnerabilities in TrueNAS."
"Best practices to operate TrueNAS in a secure manner"

2023-06-01 17:50 UTC, kmoore134 commented on content/Solutions/Optimizations/Security.md
> +Follow these best practices to minimize security vulnerabilities in TrueNAS.
"Minimize security vulnerabilities" doesn't sound great. Should focus on the positive angle, about best practices to operate TrueNAS in a secure manner.

2023-06-01 17:50 UTC, kmoore134 commented on content/Solutions/Optimizations/Security.md
> +2. Keep TrueNAS up to date with the most recent maintenance releases of the installed major version.
"Keep TrueNAS up to date with the most recently updates for your supported version"

2023-06-01 17:50 UTC, kmoore134 commented on content/Solutions/Optimizations/Security.md
> +5. Never grant TrueNAS user accounts (local or Directory Services added accounts) access to SSH or login Shells unless that account is explicitly trusted.
"to SSH or console shells"

2023-06-01 18:15 UTC, kmoore134 submitted a review, later dismissed

2023-06-01 18:42 UTC, micjohnson777 submitted a review, later dismissed
Need to fix style issues in sections mentioned in comments above the section I could not add the comments to.

2023-06-01 18:42 UTC, micjohnson777 commented on content/Solutions/Optimizations/Security.md
> +
Is this a step procedure or a list of recommendations? Parallel construction is off on a few points.

2023-06-01 18:42 UTC, micjohnson777 commented on content/Solutions/Optimizations/Security.md
>  To create an iSCSI share, go to **Sharing > Block Shares (iSCSI)** and click *WIZARD*.
line 41 the option to add should be in bold not italics.
Line 44 Initiators and Authorized Networks should be bold not italics.

2023-06-01 18:42 UTC, micjohnson777 commented on content/Solutions/Optimizations/Security.md
Line 59 Authorized Hosts and IP addresses should be bold not italics.

2023-06-01 18:42 UTC, micjohnson777 commented on content/Solutions/Optimizations/Security.md
>  However, it allows outside connections to the system and must be properly use to avoid security concerns.
incorrect use of italics in line 74, 77, 80, 83, and 85, all the UI elements should be bold

2023-06-01 20:14 UTC, micjohnson777 requested changes
The bullet list had two points that were not observing parallel construction. Made suggestions for a way to change the two points.

2023-06-01 20:14 UTC, micjohnson777 commented on content/Solutions/Optimizations/Security.md
> +* Specially modifying the base TrueNAS firmware image is unsupported and can create security issues.
Parallel construction issue, maybe this?
```suggestion
* Modifying  the base TrueNAS firmware image is unsupported and can create security issues.
```

2023-06-01 20:14 UTC, micjohnson777 commented on content/Solutions/Optimizations/Security.md
> +* Never grant TrueNAS user accounts (local or Directory Services added accounts) access to SSH or console shells unless that account is explicitly trusted.
Parallel construction issue, maybe this?
```suggestion
* Grant TrueNAS user accounts (local or Directory Services added accounts) access to SSH or console shells only if  that account is explicitly trusted.
```

2023-06-02 12:22 UTC, micjohnson777 approved these changes

2023-06-02 12:22 UTC, merged