PD-354   Procedure for updating NVDIMM - public facing
truenas/documentation pull request #1965
Opened 2023-06-09 20:53 UTC by tonyriv3

2023-06-12 12:19 UTC, Mrt134 requested changes

2023-06-14 13:01 UTC, Mrt134 commented
I'm doing a internal build and stakeholder review of this one. Keeping in draft status until we're ready to proceed.

2023-06-28 20:00 UTC, micjohnson777 requested changes
A few suggestions related to parallel construction, step procedure construction.

Excellent work!

2023-06-30 17:00 UTC, Mrt134 submitted a review, later dismissed

2023-06-30 17:05 UTC, Mrt134 approved these changes

2023-06-30 17:07 UTC, merged