PD-349   SCALE CLI - Create Auth Sessions Namespace Content
truenas/documentation pull request #2054
Opened 2023-07-26 19:16 UTC by tonyriv3

2023-08-03 18:17 UTC, micjohnson777 requested changes

2023-08-03 18:17 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +`sessions`
I think we are standardizing on the full namespace path as the example. This is not incorrect but we should use the same string start point.
```suggestion
`auth sessions`
```

2023-08-03 18:17 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +The `current` command has no required options. It returns a table showing which sessions are current. The rows of the table are relative to the rows returned from the `sessions` command.
```suggestion
The `current` command has no required options. 
Enter the command, then press <kbd>Enter</kbd>.
It returns a table showing which sessions are current. 
The rows of the table are relative to the rows returned from the `sessions` command.
```

2023-08-03 18:17 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +
Not following the template in this section.
Add the line about entering the command and the result.

2023-08-03 18:17 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +
Where do these possible states come in? Is it part of the table information returned? If it is, you can just add this in a results line, as in, "Returns true if the session is current, false if not current."

2023-08-03 18:17 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +The `internal` command has no required options. It returns a table showing if sessions are internal or not. The rows of the table are relative to the rows returned from the `sessions` command.
Include the line instructing them on how to enter the command.
```suggestion
The `internal` command has no required options. 
Enter the command, then press <kbd>Enter</kbd>.
The command returns a table showing if sessions are internal or not. 
The rows of the table are relative to the rows returned from the `sessions` command.
```

2023-08-03 18:17 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +The `origin` command has no required options. It returns a table showing the login origin of each session. The rows of the table are relative to the rows returned from the `sessions` command.
same comment above. Include the "enter the command, then press Enter line per the template.

2023-08-03 18:17 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +The `credentials` command has no required options. It returns a table showing the credentials used to authenticate each session. The rows of the table are relative to the rows returned from the `sess
same comment. Missing the enter command instruction. Also, tie in the table with the possible states so the user makes this connection better. For example, See the possible states table below for more information on what the credentials use to authenticate each session, or something similar.

2023-08-03 19:11 UTC, micjohnson777 requested changes
This review covers the sessions namespace article.
You can remove the single line paragraphs and make the three a single paragraph. 
command examples start with the parent namespace.
Otherwise excellent!

2023-08-03 19:11 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +`sessions id`
```suggestion
` auth sessions id`
```

2023-08-03 19:11 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +`sessions`
```suggestion
`auth sessions`
```

2023-08-03 19:11 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +
you can delete this empty line here in in line 32. And really all the commands. You can make these a paragraph.

2023-08-03 19:11 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +`sessions current`
```suggestion
`auth sessions current`
```

2023-08-03 19:11 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +`sessions internal`
```suggestion
`auth sessions internal`
```

2023-08-03 19:11 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +`sessions origin`
```suggestion
`auth sessions origin`
```

2023-08-03 19:11 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +`sessions credentials`
```suggestion
`auth sessions credentials`
```

2023-08-03 19:11 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLISessions.md
> +`sessions created_at`
```suggestion
` auth sessions created_at`
```

2023-08-04 18:03 UTC, micjohnson777 submitted a review, later dismissed
Just a few questions and template points. You do such good work!

2023-08-04 18:03 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLITwoFactor.md
> +* *number* is the number (in seconds) a OTP will last before expiring. Must be between 5 and 999999999999999999.
Don't use will
```suggestion
* *number* is the number (in seconds) a OTP lasts before expiring. Must be between 5 and 999999999999999999.
```

2023-08-04 18:03 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLITwoFactor.md
> +The `verify` command requires the `token` property.
if this requires the token property, then the next line should tell them how to enter the property argument (we have standard text for this in the template .

2023-08-04 18:03 UTC, micjohnson777 commented on content/SCALE/SCALECLIReference/Auth/CLITwoFactor.md
> +Enter the command, then press <kbd>Enter</kbd>.
```suggestion
Enter the command string, then press <kbd>Enter</kbd>.
```

2023-08-07 13:34 UTC, Mrt134 approved these changes

2023-08-07 13:34 UTC, merged