Pd 446 document storage snapshot namespace
truenas/documentation pull request #2091
Opened 2023-08-21 14:09 UTC by micjohnson777

This PR updates the CLIESnapshots.md article with command content and standard namespace content.
It merges into the 23.10 branch.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2023-08-21 19:54 UTC, DjP-iX commented on content/SCALECLIReference/Storage/CLISnapshot.md
> +{{< include file="/_includes/CLI/CLIGuideWIP.md" type="page" >}}
```suggestion
```

2023-08-22 14:25 UTC, DjP-iX requested changes

2023-08-22 14:25 UTC, DjP-iX commented on content/SCALECLIReference/Storage/CLISnapshot.md
> +The `rollback` command replaces data in the specified dataset with the information save in the snapshot matching the ID entered.
```suggestion
The `rollback` command replaces data in the specified dataset with the information saved in the snapshot matching the ID entered. 
```

2023-08-23 16:22 UTC, micjohnson777 commented on content/SCALECLIReference/Storage/CLISnapshot.md
> +Enclose each property arguments in the array in `[]`square brackets, with double-quoted property and values and using `=` delimiter to separate them.
agree. I just left it for now.

2023-08-23 16:23 UTC, micjohnson777 commented on content/SCALECLIReference/Storage/CLISnapshot.md
> +Use the <code>[query](#query-command)</code> command to locate the snapshot ID.
cool... I didn't know that!

2023-08-23 16:24 UTC, micjohnson777 commented on content/SCALECLIReference/Storage/CLISnapshot.md
> +`remove` command has one required property, `snapshot_remove`.
I missed that on. oops.

2023-08-23 18:25 UTC, DjP-iX approved these changes

2023-08-23 18:27 UTC, merged