Pd 450 cli guide document system config namespace
truenas/documentation pull request #2127
Opened 2023-08-31 17:24 UTC by DjP-iX

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2023-08-31 21:14 UTC, micjohnson777 requested changes
Just a few things. I didn't do the edits because I saw this in the other PR I edited so I'm just doing a review this time.

2023-08-31 21:14 UTC, micjohnson777 commented on content/SCALECLIReference/System/CLIConfig.md
> +The **config** namespace has 3 commands and is based on configuration management functions found in the SCALE API and web UI.
numbers in the 1-10 range are spelled out.
```suggestion
The **config** namespace has three commands and is based on configuration management functions found in the SCALE API and web UI.
```

2023-08-31 21:14 UTC, micjohnson777 commented on content/SCALECLIReference/System/CLIConfig.md
> +Press <kbd>Enter</kbd>.
this does not belong here. delete this line.
```suggestion
```

2023-08-31 21:14 UTC, micjohnson777 commented on content/SCALECLIReference/System/CLIConfig.md
> +Press <kbd>Enter</kbd>
```suggestion
```

2023-09-01 13:04 UTC, DjP-iX commented
Converting to draft to revisit and add warnings to the `reset` command per @kmoore134's suggestion

2023-09-12 12:35 UTC, Mrt134 approved these changes

2023-09-12 12:36 UTC, merged