PD-700 Correct Typos in CLIDataset.md
truenas/documentation pull request #2193
Opened 2023-09-26 17:08 UTC by micjohnson777

This commit/PR fixes a copy/paste error in the CLIDataset.md article.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2023-09-26 17:43 UTC, Mrt134 submitted a review, later dismissed
The file location is incorrect for master branch - you'll need (in the PD-700 branch) to move CLIDataset.md to /SCALE/SCALECLIReference/Storage/CLIDataset.md and overwrite the existing file.
Last thing will be to delete the empty /content/SCALECLIReference/ and /content/SCALECLIReference/Storage/ directories.

2023-09-26 18:19 UTC, DjP-iX approved these changes

2023-09-26 19:06 UTC, DjP-iX requested changes
Before this is merged, lines 331 and 666 both need to be changed to 

```
{{< hint type=info >}}
```

2023-09-27 18:24 UTC, DjP-iX approved these changes

2023-09-27 19:22 UTC, merged