Pd 892 investigate reporting changes including graphite
truenas/documentation pull request #2331
Opened 2023-11-29 14:23 UTC by DjP-iX

Creates documentation for the new Reporting Exporters screen/functionality.
Note: I included sectionsfor Graphite as it is the only currently supported export in the TN UI, but Netdata supports a number of other 3rd party exports and the plan is for TN to eventually support multiple Exporter types. So at that point we are probably going to need sections for the different types--this sets up the format to add those when needed. 

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2023-11-29 21:05 UTC, micjohnson777 requested changes
Found a few things that needed tweeking. In general, excellent!

2023-11-29 21:05 UTC, micjohnson777 commented on content/SCALEUIReference/ReportingScreensSCALE.md
> +| **Name** | Enter a unique name for the exporter configuration. If multiple instances are configured, each must have a distinct name. |
```suggestion
| **Name** | Enter a unique name for the exporter configuration. If configuring multiple instances, give each a distinct name. |
```

2023-11-29 21:05 UTC, micjohnson777 commented on content/SCALEUIReference/ReportingScreensSCALE.md
> +| **Enable** | Select to send reporting data to the configured exporter. Deselect to disable the explorer without removing configuration. |
```suggestion
| **Enable** | Select to send reporting data to the configured exporter. Leave checkbox clear to disable the explorer without removing configuration. |
```

2023-11-29 21:05 UTC, micjohnson777 commented on content/SCALEUIReference/ReportingScreensSCALE.md
> +| **Hostname** | Enter the hostname to add to all metrics, after the prefix, for sending data to the Graphite server. Defaults to *truenas* |
This sentence is awkward, like you had a thought, then got distracted. Not sure how to parse it.
```suggestion
| **Hostname** | Enter the host name to add to all metrics, after the prefix, for sending data to the Graphite server. Defaults to *truenas* |
```

2023-11-29 21:05 UTC, micjohnson777 commented on content/SCALEUIReference/ReportingScreensSCALE.md
> +| **Update Every** | Enter the interval to send data to the Graphite database, in seconds. Defaults to *1*. |
```suggestion
| **Update Every** | Enter the number of sections for the interval to send data to the Graphite database. Defaults to *1*. |
```

2023-11-30 13:35 UTC, DjP-iX commented on content/SCALETutorials/ConfigReportsScale.md
> +Netdata exports reporting metrics to Graphite in the format `prefix.hostname.chart.dimension`.
```suggestion
Netdata exports reporting metrics to Graphite in the format prefix.hostname.chart.dimension.
```

2023-11-30 13:40 UTC, DjP-iX commented on content/SCALEUIReference/ReportingScreensSCALE.md
> +| **Prefix** | Enter the prefix to add to all Netdata metrics sent to Graphite. Defaults to *dragonfish*. |
```suggestion
| **Prefix** | Enter the prefix to add to all Netdata metrics sent to Graphite. Defaults to *dragonfish*. <br><br>Netdata exports reporting metrics to Graphite in the format *prefix*.*hostname*.*chart*.*dimension*. |
```

2023-11-30 17:11 UTC, merged