Pd 953 update system settings advanced article content
truenas/documentation pull request #2422
Opened 2024-01-11 20:10 UTC by micjohnson777

This PR updates the System Settings > Advanced screen changes to existing widgets and the new widgets for Audit, Allow IP Addresses, and the renamed Access (formerly Sessions) widgets.

It updates the UI Ref and tutorial content in the tutorial SystemSettings/Advanced/_index.md and ManageGlobal2faSCALE.md articles.

It renames the SessionsSettingsWidget.md snippet to AccessSettingsWidget.md and updates the content.

A different PR will create new auditing content when the UI is ready.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2024-01-17 21:04 UTC, DjP-iX requested changes

2024-01-18 12:48 UTC, micjohnson777 commented on content/_includes/AccessSettingsWidget.md
> +It cannot be used to terminate the current active session.
I've reworded this in the next commit.

2024-01-18 12:51 UTC, micjohnson777 commented on content/_includes/AccessSettingsWidget.md
>  It allows administrators to manage other active sessions and to configure the token lifetime for their account.
corrections made in next commit.

2024-01-18 17:56 UTC, DjP-iX approved these changes

2024-01-18 17:56 UTC, merged