Pd 413 review v mware snapshots and storage state behavior docs
truenas/documentation pull request #2426
Opened 2024-01-17 18:34 UTC by DjP-iX

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2024-01-19 20:07 UTC, micjohnson777 requested changes
Caught a few things. Good work on the content changes and improvements!!

2024-01-19 20:07 UTC, micjohnson777 commented on content/SCALE/SCALEUIReference/DataProtection/VMwareSnapshotsScreen.md
> +Click the **Add** button to display the **Add VMware Snapshot** screen.
This is an older method of documenting the ui functions, suggest making these changes to update it to what we are currently doing.
```suggestion
**VMware Snapshot Integration**  opens the **VMWare Snapshots** screen.

{{< trueimage src="/images/SCALE/DataProtection/vmwaresnapshottask.png" alt="VMware Snapshot Integration" id="VMware Snapshot Integration" >}}

**Add** opens the **Add VMware Snapshot** screen.
```

2024-01-19 20:07 UTC, micjohnson777 commented on content/SCALE/SCALEUIReference/DataProtection/VMwareSnapshotsScreen.md
> +Configured snapshots appear on the **VMware Snapshots** screen.
```suggestion
Configured snapshots show on the **VMware Snapshots** screen. 
```

2024-01-19 21:37 UTC, DjP-iX commented on content/SCALE/SCALETutorials/DataProtection/CreatingVMwareSnapshots.md
> +VMware snapshots can integrate VMware Tools, making it possible to quiesce VM snapshots, sync filesystems, take shadow copy snapshots, and more.
see below

2024-01-19 21:38 UTC, DjP-iX commented on content/SCALE/SCALETutorials/DataProtection/CreatingVMwareSnapshots.md
> +This allows VMware snapshots to be application-consistent instead of crash-consistent.
Quiesce and X-consistent are both sort of terms of art when it comes to VMware so they need to be used, but I've added a bit more explanation here.

2024-01-19 21:44 UTC, DjP-iX commented on content/SCALE/SCALETutorials/DataProtection/CreatingVMwareSnapshots.md
> +3. In the VMWare ESXi Host Client, go to **Storage**, select **Adapters**, and then click **Software iSCSI** to configure the iSCSI connection.
ESXi Host Client is the product name

2024-01-22 14:23 UTC, Mrt134 approved these changes

2024-01-22 14:23 UTC, merged