PD-995: Sandbox (SCALE Jails) article
truenas/documentation pull request #2445
Opened 2024-01-26 18:41 UTC by Mrt134

Adapt internal notes into a small Sandboxes (Jails) article with cautions about support and being a community-only feature.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2024-01-26 20:35 UTC, DjP-iX submitted a review, later dismissed

2024-01-29 14:44 UTC, Jip-Hop requested changes

2024-01-29 14:44 UTC, Jip-Hop commented on content/SCALE/GettingStarted/SCALEReleaseNotes.md
The word **users** looks like a typo to me. Looks good otherwise!

2024-01-29 16:00 UTC, DjP-iX approved these changes

2024-01-29 16:02 UTC, merged