DOCS add secure application acces draft
truenas/documentation pull request #2450
Opened 2024-01-30 13:56 UTC by fabianmuehlberger

I started writing a tutorial regarding security of TrueNAS applications. 

I would have created an Issue for my proposal but created a fork and PR instead. Furthermore, I am not sure if this belongs in master since it is still a draft, but wanted some feedback. Since I am relatively new to TrueNAS it is likely that my contribution contains errors.

I for now I created a _index.md with the content, under Apps/AppSecurity and stored the images under src/static/SCALE/Apps. In frontmatter I added the author (me) and set draft: true

Guidance for further work is appreciated!

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2024-01-30 16:44 UTC, DjP-iX requested changes
Thank you for the excellent contribution @fabianmuehlberger!

I've left a number of (largely stylistic) suggestions, but the overall procedure looks good. 

Note that we're probably going to move this from an index to something like /apps/SecuringApps.md before publishing, but leaving it here for now will let you see the suggestions easier.

2024-01-30 16:44 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +The Cloudflare Tunnel is a client that runs on the TrueNAS SCALE system and proxies traffic from the Cloudflare network to the application.
```suggestion
[Cloudflare Tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/) is a client that runs on the TrueNAS SCALE system and proxies traffic from the Cloudflare network to the application.

{{< trueimage src="/images/SCALE/Apps/CloudflareTunnelOverview.jpg" alt="Cloudflare Tunnel Overview" id="Cloudflare Tunnel Overview" >}}

```

2024-01-30 16:44 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +In the Cloudflare One dashboard, set a public hostname for accessing Nextcloud, this hostname, in this example it is:  **nextcloud.example.com**
```suggestion
In the Cloudflare One dashboard, set a public hostname for accessing Nextcloud, for example:  *nextcloud.example.com*.
```

2024-01-30 16:44 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +The Cloudflare Tunnel is a client that runs on the TrueNAS SCALE system and proxies traffic from the Cloudflare network to the application.
Note we should add a credit to Cloudflare for the overview image

2024-01-30 16:44 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +It is highly recommended to read the [tunnel documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/) or to watch [this](https://www.youtube.com/watch?v=eojWaJQv
```suggestion
This guide assumes that the applications run as a docker container but the same approach can be used to secure apps running on Truenas Scale in Kubernetes.
 [This video](https://www.youtube.com/watch?v=eojWaJQvqiw) from Lawrence Systems provides a detailed overview of setting up Cloudflare tunnels for applications. 
```

2024-01-30 16:44 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +The service Type is set to **HTTPS** and the URL is the local TrueNAS IP + the Nextcloud container port, e.g. 192.168.1.1:9001
```suggestion
Set service **Type** to **HTTPS**.
Enter the local TrueNAS IP with the Nextcloud container port, for example *192.168.1.1:9001*.

{{< trueimage src="/images/SCALE/Apps/CloudflareTunnelHostname.png" alt="Cloudflare Tunnel Hostname" id="Cloudflare Tunnel Hostname" >}}

```

2024-01-30 16:44 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +Additional application Settings > TLS > No TLS Verify = Enabled
```suggestion
Go to **Additional application Settings**, select **TLS** from the dropdown menu, and enable **No TLS Verify**.

{{< trueimage src="/images/SCALE/Apps/CloudflareTunnelTLSSetting.png" alt="Cloudflare Tunnel TLS Setting" id="Cloudflare Tunnel TLS Setting" >}}

```

2024-01-30 16:44 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +[overwrite.cli.url](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#overwrite-cli-url) and [overwritehost](https://docs.nextcloud.com/serv
```suggestion
Install the [Nextcloud]({{< relref "/scale/scaletutorials/apps/communityapps/installnextcloudmedia.md" >}}) community application.

Click **Add** next to **Nextcloud environment** to configure the environment variables [overwrite.cli.url](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#overwrite-cli-url) and [overwritehost](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#overwritehost).
```

2024-01-30 16:44 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +In the Nextcloud App the environment variables are edited as shown below, where `value` is the address.
```suggestion
Enter the two environment variables in **Name** as *OVERWRITECLIURL* and *OVERWRITEHOST*.

Enter the address for the Cloudflare Tunnel configured above in **Value**, for example *nextcloud.example.com*.

```

2024-01-30 16:44 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +{{< trueimage src="/images/SCALE/Apps/NextcloudEnviromentVariables.png" alt="Nextcloud Environment Variables" id="Nextcloud Environment Variables" >}}
At the end can we wrap up the procedure with a step for confirming the configuration succeeded? Maybe something like wait for the installed application to deploy and then access via the proxy URL?

2024-01-30 18:51 UTC, fabianmuehlberger commented
Hey @DjP-iX thank you for the prompt reply. Since I went through the process of setting up those applications (first time TrueNAS owner), I thought I write it down while I have it in memory. 

Preferably, if you like, I would commit to e.g. "DEV DOC appsecurity" branch created by you. Otherwise, I can stay on my fork if you prefer that. 

TY for the suggestions, I hope to implement them tomorrow. 

> Note that we're probably going to move this from an index to something like /apps/SecuringApps.md before publishing, but leaving it here for now will let you see the suggestions easier.

Regarding the doc structure, I intend to cover multiple ways of securing applications, including Cloudflare, Tailscale, etc. ideally in a more generalized approach, and with the help of the community.  
I am not sure about the document structure, depending on the covered areas and apps, I think it should be split into different pages, for easier editing. 

Best Fabian

2024-01-30 23:27 UTC, fabianmuehlberger commented
Regarding the image credit, I tried to use "caption" 

{{< trueimage src="/images/SCALE/Apps/CloudflareTunnelOverview.jpg" alt="Cloudflare Tunnel Overview" id="Cloudflare Tunnel Overview" **caption="cloudflare.com"** >}} but that does not work.  How should I give credit correctly?

2024-01-31 11:02 UTC, fabianmuehlberger commented
I am not sure how to add a relative ref to an anchor.

line 24: See [security]{{< relref "_index.md#additional-security-considerations" >}}

2024-01-31 14:10 UTC, DjP-iX submitted a review, later dismissed
Looking good @fabianmuehlberger!

If you're planning to contribute additional articles on this subject, then I think we are fine to leave this as an index instead of an individual article.

2024-01-31 14:10 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +Nextcloud should now be reachable via nextcloud.example.com and use a https connection.
```suggestion
Nextcloud should now be reachable via nextcloud.example.com, using a https connection.
```

2024-01-31 14:10 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +Use strong user passwords and cofigure 2FA for additional security. [Two Factor Authentication](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/two_factor-auth.html)
```suggestion
Use strong user passwords and configure [Two Factor Authentication](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/two_factor-auth.html) for additional security.
```

2024-01-31 14:10 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +Cloudflare offers Access policies to restrict access to the application to specific users, emails or authentication methods. You can find more information in the [applications documentation](https://
```suggestion
Cloudflare offers [access policies](https://developers.cloudflare.com/cloudflare-one/policies/access/) to restrict access to the application to specific users, emails or authentication methods.
```

2024-01-31 14:10 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +Go to **Access**, click **Add an Application** button and select **Self-Hosted**
```suggestion
Go to **Access**, click **Add an Application**, and select **Self-Hosted**.
```

2024-01-31 14:10 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +Add your nextcloud application and the domain you configured in the Cloudflare tunnel.
```suggestion
Add your Nextcloud application and the domain you configured in the Cloudflare tunnel.
```

2024-01-31 14:10 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +Create a new new Policy by entering a **Policy Name**. Groups can be assigned to this policy or additional rules can be added.
```suggestion
Create a new policy by entering a **Policy Name**. Groups can be assigned to this policy or additional rules can be added. 
```

2024-01-31 14:10 UTC, DjP-iX commented on content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
> +> Note, that there are additional options for configurations, that are beyond the scope of this tutorial.
```suggestion
Note: there are additional options for policy configuration, but these are beyond the scope of this tutorial.
```

2024-01-31 14:58 UTC, fabianmuehlberger reviewed
For splitting the document, I suggest, having everything related to a specific app (in that case, Cloudflare separated).

I would keep it as it is, until there is new content.

2024-01-31 18:27 UTC, DjP-iX approved these changes

2024-01-31 19:25 UTC, merged

2024-01-31 19:25 UTC, DjP-iX commented
Thanks again @fabianmuehlberger!

This one is merged, but feel free to continue working in your branch and open a PR against our Master branch if you have any further changes. Likewise if you do write any further content for other apps/solutions. We'll be happy to see your contributions.

2024-01-31 19:59 UTC, fabianmuehlberger commented
Thank you for the support and lending me a hand! This was my first bigger contribution to a project.