Pd 1461 home directory content updates
truenas/documentation pull request #3086
Opened 2024-09-30 17:36 UTC by micjohnson777

This PR updates the home directory information in the ManagingLocalUsersSCALE.md article, grouping all home directory content together in the Configuring a User section, Adds two new screenshots, and adds a section on Adding a Home Directory to make it easier to find this content.

This information can be backported to 24.10 and 24.04 branches.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2024-09-30 17:37 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/PD-1461

2024-10-04 12:31 UTC, linzi-ix requested changes

2024-10-04 12:31 UTC, linzi-ix commented on content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
>  {{< trueimage src="/images/SCALE/Credentials/AddUserHomeDirPermSCALE.png" alt="Add User Home Directory" id="Add User Home Directory" >}}
this image is 404ing on my local build

2024-10-09 20:48 UTC, micjohnson777 commented on content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
>  {{< trueimage src="/images/SCALE/Credentials/AddUserHomeDirPermSCALE.png" alt="Add User Home Directory" id="Add User Home Directory" >}}
fixed in new commit

2024-10-11 12:33 UTC, linzi-ix approved these changes

2024-10-11 12:33 UTC, merged

2024-10-11 12:33 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.