PD-1470 / 25.04 / PD-1470-document-installing-nvidia-drivers
truenas/documentation pull request #3091
Opened 2024-10-01 15:15 UTC by linzi-ix

Screenshot uploaded of new checkbox option and small description made.
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2024-10-01 15:15 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/PD-1470

2024-10-01 15:29 UTC, Simoneu01 reviewed
In the screenshot, `NVIDIA `is misspelt `NDIVIA`

2024-10-02 11:47 UTC, micjohnson777 requested changes
A few suggested improvements for clarity and better information flow.

2024-10-02 11:47 UTC, micjohnson777 commented on content/TruenasApps/_index.md
> +Beginning in TrueNAS 24.10, NVIDIA drivers are no longer automatically installed. Users must instead manually install drivers from the TrueNAS UI.
How about this instead
```suggestion
Beginning in TrueNAS 24.10, NVIDIA drivers are no longer automatically installed. Users must manually install drivers from the TrueNAS UI.
```

2024-10-02 11:47 UTC, micjohnson777 commented on content/TruenasApps/_index.md
> +
When writing a procedure, start steps with the verb action. Remember parallel construction principles apply and procedures are about the action. You can add clarification after the action or just add the result of the action. See the suggested changes below.

2024-10-02 11:47 UTC, micjohnson777 commented on content/TruenasApps/_index.md
> +4. To complete installation, check the **Install NVIDIA Drivers** checkbox, and click **Save.**
```suggestion
If running TrueNAS 24.10 or higher:
1. Go to **Apps > Installed** and click on the **Configuration**.
   
2. Click on **Settings** to open the **settings configuration panel.**
   
3. Select **Install NVIDIA Drivers**, which is available to users with compatible GPUs.
   
4. Select **Install NVIDIA Drivers**, and click **Save.**
```

2024-10-02 11:47 UTC, micjohnson777 commented on content/TruenasApps/_index.md
> +{{< trueimage src="/images/SCALE/Apps/AppsInstallNvidiaDrivers.png" alt="Install NVIDIA Drivers" id="Install NVIDIA Drivers" >}}
You can move this image up to the line between step 3 and 4 for better context.

2024-10-02 13:17 UTC, micjohnson777 approved these changes

2024-10-02 13:17 UTC, merged

2024-10-02 13:17 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.