PD-1397 / 25.04 / Pd 1397 update d raid content
truenas/documentation pull request #3125
Opened 2024-10-11 16:53 UTC by micjohnson777

This PR creates a new snippet for dRAID Group Layout content added to the CreatePool.md snippet and the dRAIDPrimer.md article.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2024-10-11 16:53 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/PD-1397

2024-10-14 17:10 UTC, linzi-ix commented on static/includes/dRaidGroupLayout.md
Is there anything barring us from utilizing the ≤ symbol here? If not, I think users might have a more automatic recognition of the classic lesser than or equal to (≤) sign.

2024-10-14 17:10 UTC, linzi-ix requested changes
one minor comment

2024-10-14 19:41 UTC, micjohnson777 commented on static/includes/dRaidGroupLayout.md
This might not translate well for global English, writing for ESL audiences.

2024-10-15 12:29 UTC, linzi-ix approved these changes

2024-10-15 12:29 UTC, merged

2024-10-15 12:29 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.