Pd 1511 update storage devices screens
truenas/documentation pull request #3151
Opened 2024-10-22 18:58 UTC by micjohnson777

This PR updates the Devices Screen and Manage Pools article content with new screenshots that apply to 24.10.

Backport this to 24.10 branch.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2024-10-22 18:58 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/PD-1511

2024-10-30 13:03 UTC, linzi-ix requested changes
two minor changes

2024-10-30 13:03 UTC, linzi-ix commented on static/images/SCALE/Storage/DevicesExtend.png
"binary file not shown" i'd check on this one :)

2024-11-05 14:09 UTC, micjohnson777 commented on static/images/SCALE/Storage/DevicesExtend.png
this image is deleted in this PR, I don't know why it is not showing the binary file.  But if you click on the option to view the file it does show the removed image.

2024-11-05 18:13 UTC, linzi-ix approved these changes

2024-11-05 18:13 UTC, merged

2024-11-05 18:13 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.