PD-1482 / 25.04 / Pd 1482 update remote replication tutorial
truenas/documentation pull request #3194
Opened 2024-11-07 16:08 UTC by micjohnson777

This PR updates both the UI ref and tutorial articles for replication tasks.

Backport this to 24.10 branch.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2024-11-07 16:08 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/PD-1482

2024-11-08 15:21 UTC, linzi-ix requested changes

2024-11-08 15:21 UTC, linzi-ix commented on content/SCALE/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
> +| **Allow Blocks Larger than 128KB** | Inactive by default and if the system does not support large block transfers. Allows replication to send large data blocks. The destination system must also sup
```suggestion
| **Allow Blocks Larger than 128KB** | Inactive by default and if the system does not support large block transfers. Allows replication to send large data blocks. The destination system must also support large blocks. This setting cannot be changed after it is enabled and the replication task is created. See [sfs(8)](https://linux.die.net/man/8/zfs) for more information. |
```

2024-11-08 15:21 UTC, linzi-ix commented on content/SCALE/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
> +| **Transport** | Select the method of connecting to a remote system for exchanging data from the dropdown list. Options:<br><li> **SSH** - Default option. Is supported by most systems. It requires a
```suggestion
| **Transport** | Select the method of connecting to a remote system for exchanging data from the dropdown list. Options:<br><li> **SSH** - Default option that is supported by most systems. It requires a previously created SSH connection on the system.<br><li>**SSH+NETCAT** - Uses SSH to establish a connection to the destination system, then uses [py-libzfs](https://github.com/truenas/py-libzfs) to send an unencrypted data stream for higher transfer speeds. This only works when replicating to a FreeNSAS, TrueNAS, or other systems with py-libzfs installed.<br><li>**LOCAL** - Efficiently replicates snapshots to another dataset on the same system without using the network. Removes **Transport Options** SSH setting options from the screen.</li> |
```

2024-11-08 15:51 UTC, micjohnson777 commented on content/SCALE/SCALETutorials/DataProtection/Replication/RemoteReplicationSCALE.md
> +With the implementation of the administration user and role-based permissions, setting up replication tasks as an admin user has a few differences from those set up when logged in as the root user.
There really isn't a better way as there are a lot of "admin/administration" mentions in this section. At one point we recommended setting up the "admin" user but now we don't due to security hardening recommendations. Admin is too predictable as a user name so mentioning admin user is just an abbreviation for administrator or administration user.

2024-11-08 15:54 UTC, linzi-ix approved these changes

2024-11-08 18:36 UTC, merged

2024-11-08 18:37 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.