DOCS-1710-webconsole
truenas/documentation pull request #537
Opened 2021-02-10 20:24 UTC by q5sys

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2021-02-12 18:48 UTC, ericbsd commented on content/Contributing/Webconsole.md
> +In the upper right, set Persist Logs.
in 78 and higher here is a gear at the right with Persist Logs and Show timestamps.

2021-02-12 18:51 UTC, ericbsd submitted a review, later dismissed
LGTM

2021-02-12 21:46 UTC, Mrt134 requested changes
There are additional style elements that need to be done with this content and some additional organizational considerations - I will be reworking this PR next week for inclusion in the docshubtwo branch.

2021-02-17 13:10 UTC, Mrt134 approved these changes

2021-02-17 13:10 UTC, merged